from __future__ import annotations

from pathlib import Path


OPERATIONAL_MAP_FILENAME = "operational-map.md"


def render_operational_map(unit_id: str, name: str) -> str:
    return "\n".join(
        [
            "# Current Operational Map",
            "",
            f"Harness unit: `{name}` (`{unit_id}`)",
            "",
            "Use this map as current orientation. Update it when the harness unit's workflow, evidence needs, or environment assumptions change. The agent should still reason from the task, inspect available evidence, and choose the most appropriate test/evaluation strategy.",
            "",
            "This is context and navigation, not a rigid procedure.",
            "",
            "## What This Harness Unit Is Trying To Improve",
            "",
            "- Current understanding:",
            "- What better may mean right now:",
            "- Open questions:",
            "",
            "## Systems, Tools, And Environment",
            "",
            "- Systems and tools it interacts with:",
            "- Environment entry points:",
            "- Reset or restart notes:",
            "- What Harneloop records:",
            "  - `target/brief.yaml`",
            "  - `environment/contract.yaml`",
            "  - `attempts/`",
            "  - `runtime/runs/`",
            "  - `runtime/artifacts/`",
            "",
            "Harneloop records mappings, but the onboarding agent must inspect the real workspace, tools, commands, endpoints, and artifact paths.",
            "",
            "## Useful Artifacts And Evidence",
            "",
            "- Currently useful artifacts:",
            "- Where artifacts usually appear before capture:",
            "- Useful structured summaries, logs, screenshots, renders, traces, or review notes:",
            "- How evidence is usually attached:",
            "  - `harneloop artifact add ...`",
            "  - `harneloop attempt observe ...`",
            "  - `harneloop candidate evidence add ...`",
            "",
            "Choose artifacts and evidence from the current task and observed result, not from habit.",
            "",
            "## Running And Resetting The Environment",
            "",
            "- Usual run path:",
            "- Usual reset path:",
            "- Manual steps still required:",
            "- Automation opportunities:",
            "",
            "## Automation And Autonomy",
            "",
            "The agent should aim to run repeated testing/improvement loops without requiring the user to manually restart apps, reinstall addons, reset services, or collect files.",
            "",
            "If automating the environment is reasonable, implement or document that automation.",
            "",
            "If automation is risky, unclear, or too expensive/time-consuming, ask the user before proceeding.",
            "",
            "## Capability Gaps",
            "",
            "Track capability gaps separately from the tools designed into the harness unit.",
            "",
            "- Operating-agent capabilities currently available: terminal, filesystem, browser, MCPs, package managers, visual inspection, database access, or other execution-time powers the current agent can actually use.",
            "- Missing operating-agent capabilities: what the current agent cannot do, why it matters, and what bottleneck or failed attempt exposed the gap.",
            "- Unit or target-agent tools: tools the harness provides to the unit or target agent as part of the unit design and environment contract.",
            "- Requested or enabled tools: local dependencies, MCP servers, package installs, browser tools, render checkers, databases, or other capabilities added during work.",
            "- Risk, cost, auth, and security notes: credentials, external access, paid APIs, user-owned accounts, network expansion, or security posture changes.",
            "- Fallbacks if the user declines: lower-quality validation, manual review point, reduced automation, alternate artifact path, or wait/stop state.",
            "",
            "Safe default: low-risk local capabilities can be installed, enabled, or built when the environment allows it. Larger dependencies, auth, secrets, external access, paid services, or security-impacting changes should be proposed first.",
            "",
            "Capability additions should be justified by observed bottlenecks, failed attempts, missing artifacts, or clear expected improvement, not added speculatively.",
            "",
            "## Existing Work And Reuse",
            "",
            "Optimize for the best verified result, not a from-scratch implementation. Inspect project-native and external tools, open-source libraries, agent skills, MCP servers, validators, datasets, examples, documentation, research, and prior harness work before rebuilding a capability.",
            "",
            "- Existing solutions inspected and search sources used:",
            "- Reused or adapted material, source, and relevant version or revision:",
            "- Purpose and expected or measured contribution:",
            "- License, attribution, compatibility, security, cost, and permission notes:",
            "- Why a custom replacement was necessary, if existing options were rejected:",
            "",
            "Review executable third-party material before trusting it. Ask first when reuse requires credentials, paid services, external access, material downloads, restrictive licenses, security-sensitive execution, or a meaningful environment change.",
            "",
            "## Known Constraints, Fragile Spots, And Open Questions",
            "",
            "- Constraints:",
            "- Fragile spots:",
            "- Open questions:",
            "",
            "## Current Assumptions To Re-Check",
            "",
            "- Assumptions:",
            "",
            "## Prior Runs, Evidence, And Decisions",
            "",
            "- Runs: `runtime/runs/`",
            "- Artifacts: `runtime/artifacts/`",
            "- Attempt plans and observations: `attempts/`",
            "- Candidate evidence: `candidates/*/evidence/`",
            "- Promotion history: `provenance/changelog.md`",
            "",
        ]
    )


def write_initial_operational_map(unit_root: Path, unit_id: str, name: str) -> Path:
    path = unit_root / OPERATIONAL_MAP_FILENAME
    path.write_text(render_operational_map(unit_id, name), encoding="utf-8", newline="\n")
    return path
